chore: git hooks update
Two issues related to `rustfmt` are solved.

1. It hangs if no files are passed.  This case is relevant for the
   commits where the source code is not changed.
2. It checks the files which are included into the file to be checked.
   Given that, the files which aren't commited are checked as well.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,8 +1,11 @@
-#!/bin/bash
+#!/bin/bash --norc
 function runChecks(){
-    if ! rustfmt --check $(git diff --diff-filter=d --name-only --cached '*.rs'); then
-        echo "Git pre-commit hook: source code format checking failure.  Refer to .githooks/pre-commit"
-        return 1;
+    local files="$(git diff --diff-filter=d --name-only --cached '*.rs')"
+    if test -n "$files"; then
+        if ! echo "$files" | xargs -d "\n" rustfmt --config skip_children=true --check; then
+            echo "Git pre-commit hook: source code format checking failure.  Refer to .githooks/pre-commit"
+            return 1;
+        fi
     fi
 
     if ! git diff --diff-filter=d --cached '*.rs' | ( ! grep -w 'dbg!' ); then
